spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        generate_statistics: false
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
        jdbc:
          batch_size: 30
  jackson:
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  datasource:
    url: jdbc:postgresql://localhost:5432/categories
    username: postgres
    password: root
  devtools:
    restart:
      enabled: true
server:
  error:
    include-stacktrace: never
  port: 8083
